name: Lint and Test Code Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.9.0'
    - name: Install dependencies
      run: npm install
    - name: Run ESLint
      run: npm run lint
    - name: Run Tests
      run: npm test
