runtime: nodejs20

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
