name: PR Milestone Checker

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  milestone-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check for Milestone
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = context.payload.pull_request;
          if (!pr.milestone) {
            core.setFailed("PR must be associated with a milestone.");
          }
